title: "Title"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ### Request Information
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to request documentation for this project!
        Please fill out the below information:
  - type: dropdown
    id: dropdown_1
    attributes:
      label: Request Category
      options:
        - Changes to existing page
        - Creation of new page
      validations:
        required: true
  - type: input
    id: input_1
    attributes:
      label: Page Title
      description: Name or location of requested page
    validations:
      required: true
  - type: textarea
    id: textarea_1
    attributes:
      label: Description
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        Add your description here.
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: I could help with the content of this documentation request.
          required: false
        - label: I could help with the technical implementation of this documentation request.
          required: false
  - type: markdown
    attributes:
      value: |
        Compare also [the Contributing Guidelines](https://docs.brightway.dev/en/latest/content/contributing/contributing.html) for this project.