name: sphinx
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core funcitonality
  - python=3.11
  # dependency management
  # data science
  - ipython
  # plotting
  - matplotlib
  # sphinx
  - sphinx
  - nbsphinx # Jupyter notebook support
  - pydata-sphinx-theme # website theme
  - sphinx-gallery # support for a specific part of the website theme
  - myst-parser # Markdown support
  - sphinx-autobuild # live-html support
  # pip packages
  - pip