name: sphinx
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.11
  # data science
  - ipython
  # sphinx
  - sphinx=5.3.0 # sphinx-design currently requires sphinx[version>=2,<5]
  - nbsphinx # Jupyter notebook support
  - pydata-sphinx-theme=0.13.0 # website theme
  - myst-parser # Markdown support
  - myst-nb # Jupyter notebook support
  - sphinx-autobuild # live-html support
  - sphinx-autoapi # to build docs from source code instead of package import
  - sphinx-design # responsive web component support
  - sphinx-notfound-page # custom 404 page
  - graphviz # for plotting dependency diagrams with sphinx-autoapi
  - gitpython # for reading the current branch name for version-switcher functionality