name: sphinx
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.11
  # data science
  - ipython
  # sphinx
  - sphinx=5.3.0 # sphinx-design currently requires sphinx[version>=2,<5]
  - nbsphinx # Jupyter notebook support
  - pydata-sphinx-theme # website theme
  - sphinx-gallery # example gallery support
  - myst-parser # Markdown support
  - sphinx-autobuild # live-html support
  - sphinx-autoapi # to build docs from source code instead of package import
  - sphinx-design # responsive web component support