# compare: https://stackoverflow.com/a/67059629/

name: 'Update Submodules'

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Update Submodules'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Update Submodules
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit Update
      run: |
        git config --global user.name 'GitHub Actions Submodule Updater'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"